### ISSUE TITLE
OpenBSD compatibility? How do I get this thinger-ma-jigger working? Maybe not native_messenger issue.

### ISSUE THREAD

**Issue by anoduck** [tridactyl/native_messenger#43] opened 2021-03-01 17:48 UTC
The required version of Nim lang was a few ahead of what was available in the "Current" repository, so I had to install Nim manually, no biggie. Once that was accomplished, the native messenger built like a top, no issues, and even the install script worked without a hitch and setup everything as it should. The problem is that tridactyl is still not recognizing the native messenger is installed and is as configured as it should be, it still says that I need to install the native messenger. 

I do suspect that this is one of those specific to OpenBSD issues, which I know little can be done to correct. 

Any suggestions on how to get the native messenger fired up?

**Comment by bovine3dom** [comment] 2021-03-01 18:10
I'm a little bit confused, you shouldn't need to build the native messenger. The install script downloads a prebuilt binary from this repository.

Have you previously had the python version of the native messenger working on OpenBSD?

Are you using anything like Firejail? You might find some useful info in this issue if you are https://github.com/tridactyl/tridactyl/issues/2406

**Comment by anoduck** [comment] 2021-03-01 18:28
Have you previously had the python version of the native messenger working on OpenBSD?

-- _No_

Are you using anything like Firejail? You might find some useful info in this issue if you are tridactyl/tridactyl#2406

-- _No Firejail, OpenBSD uses unveil, which is currently enabled to allow all of $HOME in unveil.main._

----

_I am finding out, your plugin is not the only one failing to work on this platform. All plugins that require an external executable fail to work. For Example [Sam's Bukubrow](https://github.com/samhh/bukubrow-host) and keepassxc browser integration._

_I think it would probably be best to bring the issue to the attention of the OpenBSD firefox port/package maintainer, since it seems to be both all plugins of a certain type and a specific to OpenBSD issue._

**Comment by Rummskartoffel** [comment] 2021-03-01 18:51
My guess is that the [native manifest location](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#manifest_location) needs to be different on OpenBSD. Unless of course native messengers aren't supported, but I'd expect that to be noted in the port's readme or something of the sort if it were the case.

**Comment by bovine3dom** [comment] 2021-03-01 19:05
In which case probably a dupe of https://github.com/tridactyl/tridactyl/issues/1144

**Closed by bovine3dom** 2021-03-01 19:05 UTC

**Comment by anoduck** [comment] 2021-03-02 21:44
@bovine3dom You are correct, appears to be a dupe. My sincere apologies. Thank you for the assistance.
